### ISSUE TITLE
Change behaviour of Channels button in Control panel

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#195]
Currently one large tree in a widget with all the info for all channels is created when the Channels button is pressed in the Control panel.

A better alternative is:
- Create another control panel with the names of all of the channels
- When one of these buttons is pressed, a widget with just that ion channel is created (with content expanded) and a set of activation curve graphs (as in the OSB 3D explorer view of *.channel.nml file) are created.

**Comment by adrianq** [comment]
Sounds like a good idea. Some thoughts/doubts:
- Another control panel can mean too many widgets floating on the screen. Specially considering that the name of the channels can be too long.
- The information about the channels is going to be generated from the neuroml parsed by Geppetto or from the export library. If we go for the second option we would have to change the info writer in order to identify the channels with some kind of field that can be match to the domainType field in Geppetto or something similar. Anyway if it is part of the summary I don't know if it is a good idea to match it to the domainType in Geppetto. (To be discussed with @tarelli)
- If we open a widget with the information about the ion channel and then a widget for every curve maybe we would have a screen full of widget. Specially the second time you click in a channel button. Maybe some kind of mechanism to remove the open widget and show the new ones.

**Comment by pgleeson** [comment]
Fixed with latest release
