### ISSUE TITLE
Ease of initiation of simulations; no console interaction required

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#218]
Scenario:

- [x] User loads a NeuroML project 
- [x] Persists project (gets warning if not logged in)
- [ ] Presses Run
- [ ] New widget launched to set options for:
  - simulation duration
  - dt
  - what to watch/record (all membrane potentials at all cell somas is default)
- [x] Simulation is launched
- [ ] When finished (and same experiment is still open) user gets notified with new widget with options to a) display variables as changing colours on 3D segments; b) choose from a list of watched variables to show in plot.

**Comment by adrianq** [comment]
@tarelli you asked me about what we have in mind for the simulation tool (I am not sure if it is going to be a widget finally) @pgleeson wrote some ideas in this issue. Find below some ideas I think it should have. I don't know if there are going to be part of the same layout, different perspective or different widgets but let's not worry about this for the moment. I am also aware about the Experiment Console that we have at the bottom but this could be something more specific or some features can be added to this console while some others can go into a widget. 
- Preparing simulations
   - Show all the variables that can be watched. If it is a network show it in a hierarchical way/
   - Watch/Unwatch variables
   - Different filter option: textfield, filter by cell, filter by parameter...
   - Different options to select which variables you want to watch: Select all, unselect all, select all variables in a cell, select a variable in each cell of this type...
   - A way to set a default configuration for a simulation. Sth like 'Run Default Simulation'. It has to be defined manually by the OSB team and it will define which variables can be watched, time step, length, experiment name... Maybe it can be done with js script and it is not an extra feature.
   - A better way to change which parameters can be changed for the simulation. At the moment, they are 'hidden' in the tree visualiser.
  - An easy way to define the timestep, length, experiment name...
  - An easy way to define specific domains parameters: target component... (we will have to define what goes into advance options).
  - It should be clear if the experiment has been persisted or not. Maybe do it automatically if the user starts playing with the watched variables or parameters (perhaps with a warning message 'This model will persisted')

-Running Simulations
   - If there is an error, an error message with information about it need to be shown. At the moment, this is the neuron log.
   - I am not sure if the colour scale in order to show the experiment status is enough. Maybe the problem is that we don't have enough help and tooltip for the users. Also it is true that the OSB 3D explorer is becoming much complex and it requires a lot of time to understand how it works.

- Reproduce Simulations
   - Define which variables you want to stream to the client. Note this is not the same as the variables you have set to be watched.
   - An easy way to plot this variables
   - Time step you want to reproduce it: step by step, every 2 step, all at once... BTW, this is related to the plot widget refactor/improvement. Because if we stream too many points it blocks the browser.
   - Graphical component to start, pause and stop the simulation
   - Graphical component to download the model and the outputs

cc @borismarin   

If sth else come to my mind I will update this card. Just for thought though.

**Comment by pgleeson** [comment]
Mustn’t forget here: selection of which simulator to use, i.e. jNeuroML_NEURON, jNeuroML_Brian etc.

Should be based on a call to existing methods for listing which output formats support the features found in the model.
