### ISSUE TITLE
Multiple errors on pages requiring email confirmations

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/redmine#332]
Emails get sent (after a delay) but page shows gateway error/502/503.

**Comment by sanjayankur31** [comment]
The issue here was that `sendmail` requires a FQDN for the `hostname`. If this is not available, `sendmail` takes over a minute to send the e-mail. This blocks the redmine server and results in the bad gateways. A fix is to ensure that the redmine container always has a FQDN as its hostname.

Current hotfix: edit `/etc/{hosts,hostname}` in the container to convert the hostname to a FQDN.

The persistent fix is to use the `hostname: ` directive in the docker-compose file. This is currently being worked on and tested.
